# Generated by Django 5.0.3 on 2024-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Menu ID')),
                ('drink', models.CharField(max_length=100, verbose_name='Drink')),
                ('sub_drink', models.CharField(max_length=100, verbose_name='Sub Drink')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['drink', 'sub_drink'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('order_dt', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price_all', models.IntegerField(verbose_name='Total Price')),
                ('order_status', models.CharField(max_length=100, verbose_name='Order Status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_dt'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('payment_dt', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('type', models.CharField(max_length=100, verbose_name='Payment Type')),
                ('payment_status', models.CharField(max_length=100, verbose_name='Payment Status')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_dt'],
            },
        ),
    ]
